import json, pathlib, subprocess, shutil, sys
BASE=pathlib.Path(__file__).parent
VID=pathlib.Path("/Users/macbookpro/Desktop/Cursor Projects/60-wave-videos/video")
PUB=VID/"public"/"ssexamples"; PUB.mkdir(parents=True, exist_ok=True)
brands={c["slug"]:c for c in json.load(open(BASE/"brands.json"))}
beats=json.load(open(BASE/"beats.json"))
align=json.load(open(BASE/"align.json"))

def wordmark(name):
    n=name.upper()
    # split so the tail carries the brand colour, like the Northbank lockup
    if " & " in name:
        a,b=name.split(" & ",1); return a.upper()+" & ", b.upper()
    parts=n.split()
    if len(parts)>1: return parts[0]+" ", " ".join(parts[1:])
    return n[:len(n)//2], n[len(n)//2:]

ready=[]
for slug,c in brands.items():
    if slug not in align: continue
    src=BASE/"src"/f"{slug}-src.mp4"
    if not src.exists(): continue
    # 25fps HeyGen source -> 30fps, DURATION-PRESERVING (never -r 30 alone)
    dst=PUB/f"{slug}-avatar.mp4"
    subprocess.run(["ffmpeg","-loglevel","error","-i",str(src),"-vf","fps=30",
        "-c:v","libx264","-crf","18","-pix_fmt","yuv420p","-c:a","aac","-b:a","128k","-y",str(dst)],check=True)
    din=float(subprocess.run(["ffprobe","-v","error","-show_entries","format=duration","-of","csv=p=0",str(src)],capture_output=True,text=True).stdout)
    dout=float(subprocess.run(["ffprobe","-v","error","-show_entries","format=duration","-of","csv=p=0",str(dst)],capture_output=True,text=True).stdout)
    assert abs(din-dout) < 0.05, f"{slug}: fps resample changed duration {din}->{dout}"
    # a still for the designed poster, taken mid-film (never frame 0)
    subprocess.run(["ffmpeg","-loglevel","error","-ss",str(round(din*0.35,2)),"-i",str(dst),
        "-frames:v","1","-y",str(PUB/f"{slug}-pip.png")],check=True)
    shutil.copy(BASE/"plates"/f"{slug}.png", PUB/f"{slug}-page.png")
    h,t=wordmark(c["brand"])
    bs=[]
    for b,st in zip(beats[slug], align[slug]["starts"]):
        e={"k":b["k"],"t":b["t"],"start":st}
        if b.get("sub"): e["sub"]=b["sub"]
        if b.get("p"): e["p"]=1
        bs.append(e)
    ready.append({"slug":slug,"brand":c["brand"],"wordmarkHead":h,"wordmarkTail":t,
        "recipient":c["recipient"],"hue":c["hue"],"voLen":align[slug]["voLen"],"beats":bs})

ts=VID/"src"/"ssExamplesData.ts"
ts.write_text("// GENERATED by scratchpad/build/emit.py -- do not hand-edit.\n"
  "// Beat starts are forced-aligned against each render's own baked audio.\n"
  "import type { FilmData } from \"./SsExamples\";\n\n"
  "export const FILMS: FilmData[] = " + json.dumps(ready, indent=1) + ";\n")
print("emitted", len(ready), "films:", ", ".join(f["slug"] for f in ready))
